pub struct SamplesByChannel<T> {
    front_left: Option<T>,
    front_right: Option<T>,
    front_center: Option<T>,
    low_frequency: Option<T>,
    back_left: Option<T>,
    back_right: Option<T>,
    front_left_of_center: Option<T>,
    front_right_of_center: Option<T>,
    back_center: Option<T>,
    side_left: Option<T>,
    side_right: Option<T>,
    top_center: Option<T>,
    top_front_left: Option<T>,
    top_front_center: Option<T>,
    top_front_right: Option<T>,
    top_back_left: Option<T>,
    top_back_center: Option<T>,
    top_back_right: Option<T>,
}